Add datadog_enabled to ingress-nginx
XenitAB/terraform-modules pull request #385
Opened 2021-08-30 14:22 UTC by NissesSenap

Thanks to this datadog will be able to get metrics from nginx

2021-08-30 14:27 UTC, NissesSenap commented
With the following annotation to the nginx pods:

```.yaml
  annotations:
    ad.datadoghq.com/controller.check_names: '["nginx_ingress_controller"]'
    ad.datadoghq.com/controller.init_configs: '[{}]'
    ad.datadoghq.com/controller.instances: '[{"prometheus_url": "http://%%host%%:10254/metrics"}]'
```

and I can see the data in datadog

![image](https://user-images.githubusercontent.com/14774899/131354428-52f173cf-13f6-4216-9977-bc9414e44586.png)

I need to verify what happens if `podAnnotations` is left empty without datadog nor linkerd is used...

I also think that it might be interesting to get nginx data to datadog, right now we only send ingress-controller data.
For more documentation see: https://docs.datadoghq.com/integrations/nginx_ingress_controller/?tab=containerized

I will continue on this tomorrow.

2021-08-30 16:47 UTC, simongottschlag requested changes

2021-08-30 16:47 UTC, simongottschlag commented on modules/kubernetes/ingress-nginx/templates/values.yaml.tpl
> -  %{~ if linkerd_enabled ~}
I would prefer it if we keep this if statement and adding `|| datadog_enabled`

2021-08-31 09:36 UTC, NissesSenap commented
After a discussion with @simongottschlag we think that the data that we get from nginx-ingress-controller /metrics page should be enough to get the data that we need. Sadly the datadog docs isn't up to data so it sent me on a longer configuration trip then I have hoped for.
Any way please review again and hopefully this should be enough.

2021-08-31 10:54 UTC, simongottschlag approved these changes
LGTM 😊👍🥇

2021-08-31 12:29 UTC, NissesSenap commented
@simongottschlag can you take a second look? 
I missed the azure addition in my last PR.

2021-08-31 13:01 UTC, simongottschlag approved these changes

2021-08-31 13:02 UTC, merged