Default ingressClassName for ingress_healthz
XenitAB/terraform-modules pull request #821
Opened 2022-09-29 12:32 UTC by NissesSenap

This to remove issues in e2e tests.

2022-09-29 12:33 UTC, NissesSenap commented on modules/kubernetes/aks-core/modules.tf
> +  public_private_enabled = var.ingress_config.public_private_enabled
Do we think it's a good idea to use this config variable that should be used for ingress-nginx?

2022-10-18 06:48 UTC, jimgus requested changes

2022-10-18 06:48 UTC, jimgus commented on modules/kubernetes/ingress-healthz/main.tf
> +  ingress_class_name = var.public_private_enabled == true ? "nginx" : "nginx-public"
The other way around

2022-11-03 11:50 UTC, jimgus approved these changes
LGTM!

2022-11-03 12:54 UTC, merged